import React from 'react'

export const AT_text = (
    <p className="interview-text">
        Alex is the Co-Founder and CEO of Mlkmn, a Philadelphia-based startup that provides a sustainable and affordable option for household item delivery and refills. He lives and works in Rittenhouse, the 15-minute mecca of Philly. He has access to 50% more amenities than John, who lives in Graduate Hospital, and almost 5 times the amenities as Bob living in Mt Airy. He hasn’t owned a car in nearly 10 years, and a driving factor (pun… intended) when he and his fiancé consider places to live is that they would not be inconvenienced without a car. This is a choice of lifestyle: they embrace the habit of picking up a couple groceries for dinner each day rather than going to a box store each week–– and when their grocery is three minutes from home, this is not an issue. The sustainability benefit of not having a car is emboldening but not deciding.
        <br /><br />
        Alex gets to the majority of his amenities on foot. He has access to the same number of amenities just by walking as Bob, Melanie, Maura, and Vicky do using all three modes of transit. He uses his bike to get to places further than a 15-minute walk, or just to speed up his travel time. Alex says transit is a distant third option for transportation. He doesn’t think SEPTA is any more efficient than using his bike, nor does it measure up to the public transit he’s experienced in other cities. While these high rates of accessibility allow Alex to live the lifestyle he chooses, this neighborhood comes with a premium. The amenities he utilizes are more expensive than what is offered elsewhere. While he can walk out his front door and immediately see 8 coffee shops, there’s nowhere to get a cheap beer and a hot dog.
        <br /><br />
        He also says that having so many amenities in close proximity, combined with a demanding work schedule, means that he rarely leaves his neighborhood. While he would enjoy getting out to Fishtown to go to a restaurant or bar, he has no reason to even go in that direction in his day-to-day movements. If he did make an effort to go, he would need to take an Uber. While decentralization is often described as a benefit of 15-minute cities, the goal is not to create insular, “all-purpose” neighborhoods. Transit connectivity between neighborhoods is also essential to promote a car-free lifestyle that is not geographically or culturally limited.
        <br /><br />
        Alex also pointed out that, from a planning perspective, there are benefits to centralized commercial zones. A service truck making deliveries is less efficient and more disruptive in a small residential neighborhood than in Center City. This reveals that cities operate in ways which have been accepted as the most efficient and cost-effective within the current system, but may not be optimal in a entirely 15-minute city. Startups like Mlkmn bring creative solutions to these problems. The demand for these solutions are increasing as cities and city-dwellers become more conscious of sustainability and logistical inefficiency.
    </p>
)

export const JH_text = (
    <p className="interview-text">
        John lives in Graduate Hospital with his wife and two high-school-aged kids. He works at the University of Pennsylvania as a researcher and lecturer focused on digital preservation, and doesn’t mind walking the 20-block commute. He also bikes around the city to visit work sites, which he finds more flexible and practical than using transit in most cases. He finds owning a car necessary to transport his kids to school or activities and to shop for groceries and other household items for the family. This demonstrates the different amenity needs and transportation considerations for parents and families.
        <br /><br />
        Based on the results of this algorithm, John has access to the second highest number of amenities following Alex, who lives in Center City. However, the majority of these amenities are only accessible via bicycle. While this is a trend on all the maps, it is particularly extreme in Graduate Hospital.
        <br /><br />
        While biking is a very useful mode of transit in some cases, as in John’s work, it is not suitable for all trips. Many of the amenities that would be only accessible by bicycle from this neighborhood are not practical options. For amenities such as retail or groceries, you may need to purchase more items than you can carry home. For restaurants, schools, or entertainment, you may be traveling at night or with family, where biking is not ideal.
        <br /><br />
        The amenities that are accessible via transit are clustered closer to Center City, while other amenity hubs such as University City, Passyunk Ave, and Queen Village are not accessible by transit within 15 minutes. This indicates that public transit is not as connective outside Center City. There are also very few amenities within walking distance.
        <br /><br />
        These trends are reflected in John’s responses. He concluded that there are amenities within the neighborhood that fit each of the categories, but the options are limited and not sufficient to meet the entirety of his family's needs. He partially attributes it to the neighborhood’s character; large retail stores or entertainment venues are not conducive to the residential fabric of the neighborhood. In order for a 15-minute city to work for families and kids, there need to be neighborhoods in which the amenities augment residential culture and transportation options which are convenient and safe for all ages.
    </p>
)

export const ZR_text = (
    <p className="interview-text">
        Zoey lives on the West side of University City. While she owns a car, it’s not unusual for her to go a week without using it. She accesses most of her amenities on foot, and is happy with the restaurants, retail offerings, and greenspace available to her in University City and West Philly. When the weather is nice, she will frequently bike places, but only during the daytime. She will use the trolley or the MLF subway line to get to appointments or run errands, but she doesn’t like using the bus due to bad experiences commuting to high school when she was younger.
        <br /><br />
        When Zoey does need her car, it is usually to get across the city to Fishtown or South Philly to go to a restaurant, see friends, or attend tango dancing class. While these routes would not fall in the 15 minute range via transit, there are transit options that connect these parts of the city. However, Zoey doesn’t take transit or walk at night, which is when most of these activities fit in her schedule. As a woman, she does not feel safe in these situations, especially while alone. Even when she does drive, it is possible she will have to walk several blocks home, as she doesn’t have guaranteed street parking. In these circumstances, she weighs whether the price of rideshare is worth the sense of security she gains from a door-to-door trip.
        <br /><br />
        Of all the people I talked to in this project, every woman had some sort of physical safety concern around using one of these transit modes. None of the men said they felt unsafe walking, biking, or on transit, even at night. Safety and crime rates, particularly directed at women, are deeper cultural problems that are experienced all over the country and world, and will not be solved just by making a perfectly 15-minute city. However, as Maura talks about in her interview, fostering positive public transportation culture can make a big difference in the experience of transit for everyone. In addition, a deeper sense of community belonging can increase safety and security while moving through your neighborhood. The 15-minute city would make a positive impact on both of these factors, and serve as a place to start when addressing these larger gendered social issues.
    </p>
)

export const MY_text = (
    <p className="interview-text">
        Melanie grew up taking SEPTA for multiple hours each day to get to school. She lived in West Oak Lane but attended private and magnet schools outside her neighborhood. She found waiting for the bus and making multiple transfers to be a hassle. Because of this, she was eager to get a car and have more independence. She got a bachelor's degree in Urban Studies and a masters degree in Education, then moved back to West Oak Lane to work as a teacher and has recently started her own tutoring company. Melanie still uses transit occasionally, and prefers the subway to the bus, but overall finds driving to be preferable for the majority of her needs.
        <br /><br />
        Melanie often drives to get to other neighborhoods. She feels safe walking or biking around her house, but doesn’t find it aesthetic or enjoyable. She’s more likely to drive a short distance to go for a bike ride or walk, or to access amenities. Her strategy for going downtown is to find parking in Spring Garden and walk the remaining blocks to Center City. In an ideal 15-minute city, these trips could be accomplished by a more accessible and enjoyable public transportation system.
        <br /><br />
        Even though Melanie admits she could utilize SEPTA more, ultimately she thinks that her neighborhood fails to meet the qualifications of a 15-minute city for her because of the available amenities. She says West Oak Lane is underdeveloped––though there is space to build, many lots remain vacant. Also, the options of amenities that are in the neighborhood are not her first choice––for example, there are restaurants around, but she would only get takeout from them. If she wanted a sitdown meal, she would have to travel further and probably take her car. If quality amenities were closer and more accessible, Melanie says she would use her car less. The data supports Melanie's argument, but doesn't tell the whole story. She does have a low number of results in each category compared to the other interviewees––however, Bob and Vicky have a similar number of amenity results in the adjacent neighborhood of Mt Airy, yet express much more satisfaction with the offerings. Clearly, not all amenities are created equal, and there is a discrepancy between the quality of amenities between neighborhoods.
    </p>
)

export const MJ_text = (
    <p className="interview-text">
        Maura was born and raised in North Philly, attended Drexel, and now lives in East Germantown and works in community outreach. For most of her adult life, Maura’s “fun fact” about herself was that she didn’t have a driver’s license. She got one last year at age 27, but still doesn’t own a car. This has given her a unique perspective on transportation and plenty of experience walking, biking, and using public transit in the city.
        <br /><br />
        Maura recognizes SEPTA is an imperfect system. She says operational inefficiency and imperfect planning are major problems. However, after years of relying on it as the primary way to get around the city, she believes that if people care enough about the idea of transit then they can get past these flaws.
        <br /><br />
        Maura has mastered the “functional commute”. If she is using transit to get to work or run errands, she knows where to get off to grab groceries or go to her favorite restaurant before resuming her travels to her next destination. She used to ride an Indego bike to the gym as part of her workout. These habits make transportation more productive and efficient, and seem to have been developed as a product of adapting to live without a vehicle.
        <br /><br />
        Maura studied abroad in Tokyo, one of the transportation capitals of the world, and compared her experiences in Japan and Philadelphia. The attitude towards public transit in Japan is very positive, whereas in Philly she sees it stigmatized as dirty, unsafe, or inconvenient. She says that transit systems in Japan are service-oriented: they take pride in creating a positive environment on their buses, subways, and high speed trains, and there are many route options with predictable and frequent stops. This quality of service not only makes it fast and easy to get around, but permeates the culture and public view of transportation to create vastly different experiences in each place. She also noticed a difference in attitude towards cars. While in Japan owning and regularly using a car was rare, in Philadelphia it is so common that she was an anomaly that she did not have a license or car as a young adult. Some of the car-oriented design decisions that shape Philadelphia frustrate her as a pedestrian and user of transit.
        <br /><br />
        Maura described her street as the border between the “hood”and a very affluent area. Her neighborhood is diverse in race and income. She finds that walking just 5 minutes in either direction are very different experiences. For example, although there is a grocery store within walking distance, it’s not a pleasant walk or transit ride to get there, so she shops at a store further away. These neighborhood dynamics are not captured from running a routing algorithm or looking at a map, yet are integral to defining the accessibility of amenities.
    </p>

)

export const BW_text = (
    <p className="interview-text">
        Bob was my high school physics teacher in Rhode Island. He relocated to Philadelphia last November and now teaches at Germantown Friends and lives with his wife in Mt Airy.
        <br /> <br />
        When I first explained the concept of the 15-minute city, Bob immediately replied with, “I live in that city!”. When moving to Philadelphia, Bob was conscious that he wanted to live in a walkable neighborhood near his work where he could access a variety of amenities without relying on his car, and Mt Airy fits all of those requirements. While he and his wife own a car, he uses it rarely and hopes to eventually not need it at all. His primary motivation to bike, walk, and use transit is sustainability.
        <br /> <br />
        Based on Bob’s experience living in Mt Airy, it seems to be a near-perfect 15-minute neighborhood. However, the data tells a different story. The algorithm run from his residence returned the least number of amenities of all the interviewees. While there were results for each category, they were significantly fewer than in other locations. This suggests that the quantity of amenities is not the defining factor in how one might experience their 15-minute city.
        <br /> <br />
        Rather, more influential in defining the 15-minute city seem to be the quality and accessibility of amenities. There is a certain degree of subjectivity in how one defines a “quality” amenity based on individual preference and cultural belonging. Bob finds Mt Airy a strong cultural fit. He expressed that he finds the amenities offered in his neighborhood to be well-suited to his needs and preferences, and that he and his neighbors are very like-minded. In addition, Bob is comfortable using all three modes of transportation and can very easily move about his neighborhood to access these amenities. As an able-bodied, white male living in an affluent neighborhood, he possesses a degree of privilege that may factor into this high level of accessibility. He also is strongly motivated by his desire to minimize his carbon footprint, and his transportation decisions reflect this.
    </p>
)

export const VK_text = (
    <p className="interview-text">
        Vicky is a lifelong Philadelphian who grew up in Northeast Philly and has since lived in neighborhoods all over the city. She currently works in the Urban Studies department at the University of Pennsylvania and lives off Germantown Avenue in Mt Airy with her husband.
        <br /><br />
        Vicky maintains that there is no “perfect neighborhood” in Philadelphia––each has tradeoffs. She chose to move to Mt Airy because it is as close as she’s found to her ideal neighborhood. She enjoys that it is safe and walkable. She finds the amenities nice, but admits they’re a bit “granola” and some are catered to an older demographic. She says that this makes the neighborhood have a specific feel and considers it less urban than other parts of the city.
        <br /><br />
        The results of the routing algorithm from Vicky’s residence show the highest proportion of transit-accessible amenities of all interviewees. Living very close to Germantown Avenue, she has almost immediate access to bus stops that service route 23. This gives her access to clusters of amenities up and down Germantown Ave and in the hub of Chestnut Hill. This shows that proximity to bus stops and access to a direct route greatly reduces the total amount of time spent traveling via transit, and increases the 15-minute range of accessible locations.
        <br /><br />
        Vicky is personally opposed to biking on Philly streets due to safety concerns. She finds the driving culture in Philadelphia to be aggressive, particularly in the relationship between cars and bikes. She’s had  experiences that have affirmed this in her time living in different Philadelphia neighborhoods, with some areas being worse than others. Although she thinks bike infrastructure helps the issue, it’s not enough to protect bikers from serious injury. Her husband bikes, and they’ve installed a camera on his helmet so she can avenge his death if necessary (...knock on wood). Consistently in the neighborhoods of each interviewee, biking can reach the highest number of amenities. Transit has a comparable distance radius, but is restricted by routing and scheduling, and doesn’t allow the freedom, flexibility, and recreation that biking does. However, biking is also the most dangerous and physically demanding of the 15-minute city modes. People like Vicky who choose not to take the risk of biking, or less able-bodied residents who cannot bike, will have more limited access to amenities.
        <br /><br />
        Vicky is a brunch enthusiast, and has driven 2 hours for a good brunch restaurant (Vicky's Philly  recommendation: Morning Glories in South Philly).  She uses her car for brunch excursions and other road trips. Getting out of the city is important to her and is one of the primary functions for her car. She’s used car share services in the past, but finds them to be less reliable and convenient. Most people I talked to express the need or desire to get out of the city from time to time. Unless their destination is on a Regional Rail or Amtrak route, the only way to do this is with a vehicle. If residents of a 15-minute city do not own their own car, there is a need for carshare options that are convenient and affordable.
    </p>
)
